// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLveLNSVmaudrB8WOLBe9MOsTQ3oDJO4k',
    appId: '1:474346991602:web:f6fd5413709356970cc56b',
    messagingSenderId: '474346991602',
    projectId: 'alhawta-74b34',
    authDomain: 'alhawta-74b34.firebaseapp.com',
    storageBucket: 'alhawta-74b34.appspot.com',
    measurementId: 'G-W631V7J009',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaji2w_c73l8JTrjVIwZibw0LuApwet-g',
    appId: '1:474346991602:android:1e11ce69a9b66b030cc56b',
    messagingSenderId: '474346991602',
    projectId: 'alhawta-74b34',
    storageBucket: 'alhawta-74b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe_ahenWdmlW5pTdQ9dBRRhx225wkVSu0',
    appId: '1:474346991602:ios:dac1046913d4a7d70cc56b',
    messagingSenderId: '474346991602',
    projectId: 'alhawta-74b34',
    storageBucket: 'alhawta-74b34.appspot.com',
    iosBundleId: 'com.ezriouil.alhawta',
  );
}
